<a href="https://colab.research.google.com/github/Elakkiyasree13/Recruiterai/blob/main/fds2ques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

marks = [50,80,65,88,70,95,40,98,85,90]
df = pd.DataFrame(marks, columns=["Marks"])
df

   Marks
0     50
1     80
2     65
3     88
4     70
5     95
6     40
7     98
8     85
9     90

In [2]:
freq = pd.cut(df["Marks"], bins=5).value_counts().sort_index()
cum_freq = freq.cumsum()

print("Frequency:\n", freq)
print("\nCumulative Frequency:\n", cum_freq)

Frequency:
 Marks
(39.942, 51.6]    2
(51.6, 63.2]      0
(63.2, 74.8]      2
(74.8, 86.4]      2
(86.4, 98.0]      4
Name: count, dtype: int64

Cumulative Frequency:
 Marks
(39.942, 51.6]     2
(51.6, 63.2]       2
(63.2, 74.8]       4
(74.8, 86.4]       6
(86.4, 98.0]      10
Name: count, dtype: int64

In [3]:
print("Mean:", df["Marks"].mean())
print("Median:", df["Marks"].median())
print("Mode:", df["Marks"].mode()[0])

Mean: 76.1
Median: 82.5
Mode: 40

In [4]:
print("Range:", df["Marks"].max() - df["Marks"].min())
print("Standard Deviation:", df["Marks"].std())

Range: 58
Standard Deviation: 19.46763696211969

In [5]:
mean = df["Marks"].mean()
std = df["Marks"].std()

z_scores = (df["Marks"] - mean) / std
df["Z-Score"] = z_scores

df

   Marks   Z-Score
0     50 -1.340687
1     80  0.200332
2     65 -0.570177
3     88  0.611271
4     70 -0.313341
5     95  0.970842
6     40 -1.854360
7     98  1.124944
8     85  0.457169
9     90  0.714006